# Generated by Django 5.0.1 on 2026-09-16 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('parsed_constraints', models.JSONField()),
                ('recommendation', models.JSONField(blank=True, null=True)),
                ('llm_provider', models.CharField(max_length=50)),
                ('llm_model', models.CharField(blank=True, max_length=100)),
                ('parse_latency_ms', models.FloatField()),
                ('optimization_latency_ms', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField()),
                ('is_ground_truth', models.BooleanField(default=False)),
                ('human_verified', models.BooleanField(default=False)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='intent_inte_user_id_d1785f_idx'), models.Index(fields=['llm_provider'], name='intent_inte_llm_pro_895b28_idx'), models.Index(fields=['is_ground_truth'], name='intent_inte_is_grou_e9cc1f_idx')],
            },
        ),
    ]
