# Generated by Django 5.0.1 on 2026-09-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud', models.CharField(choices=[('AWS', 'Amazon Web Services S3'), ('AZURE', 'Microsoft Azure Blob'), ('GCP', 'Google Cloud Storage')], max_length=10)),
                ('tier', models.CharField(choices=[('standard', 'Standard / Hot'), ('infrequent', 'Infrequent Access / Cool'), ('archive', 'Archive / Cold')], max_length=20)),
                ('region', models.CharField(max_length=50)),
                ('storage_per_gb_month_usd', models.DecimalField(decimal_places=6, max_digits=10)),
                ('put_cost_per_10k_usd', models.DecimalField(decimal_places=6, max_digits=10)),
                ('get_cost_per_10k_usd', models.DecimalField(decimal_places=6, max_digits=10)),
                ('egress_per_gb_usd', models.DecimalField(decimal_places=6, max_digits=10)),
                ('availability_sla', models.DecimalField(decimal_places=4, default=99.9, max_digits=6)),
                ('min_storage_duration_days', models.IntegerField(default=0)),
                ('min_billable_size_kb', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cloud', 'tier'], name='telemetry_c_cloud_9ceb81_idx')],
                'unique_together': {('cloud', 'tier', 'region')},
            },
        ),
        migrations.CreateModel(
            name='LatencyProbeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=50)),
                ('rtt_ms', models.FloatField()),
                ('p50_latency_ms', models.FloatField(blank=True, null=True)),
                ('p90_latency_ms', models.FloatField(blank=True, null=True)),
                ('p99_latency_ms', models.FloatField(blank=True, null=True)),
                ('status_code', models.IntegerField(default=200)),
                ('is_successful', models.BooleanField(default=True)),
                ('probed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-probed_at'],
                'indexes': [models.Index(fields=['cloud', '-probed_at'], name='telemetry_l_cloud_bf2516_idx')],
            },
        ),
    ]
